// Code generated by protoc-gen-go. DO NOT EDIT.
// source: compile.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CompileRequest struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Input                []string `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty"`
	ExpectedOutput       []string `protobuf:"bytes,3,rep,name=expected_output,json=expectedOutput,proto3" json:"expected_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompileRequest) Reset()         { *m = CompileRequest{} }
func (m *CompileRequest) String() string { return proto.CompactTextString(m) }
func (*CompileRequest) ProtoMessage()    {}
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c90e492e3fe2f74, []int{0}
}

func (m *CompileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompileRequest.Unmarshal(m, b)
}
func (m *CompileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompileRequest.Marshal(b, m, deterministic)
}
func (m *CompileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompileRequest.Merge(m, src)
}
func (m *CompileRequest) XXX_Size() int {
	return xxx_messageInfo_CompileRequest.Size(m)
}
func (m *CompileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompileRequest proto.InternalMessageInfo

func (m *CompileRequest) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *CompileRequest) GetInput() []string {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *CompileRequest) GetExpectedOutput() []string {
	if m != nil {
		return m.ExpectedOutput
	}
	return nil
}

type File struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c90e492e3fe2f74, []int{1}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type CompileResponse struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Build                *Response `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
	Execute              *Response `protobuf:"bytes,3,opt,name=execute,proto3" json:"execute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CompileResponse) Reset()         { *m = CompileResponse{} }
func (m *CompileResponse) String() string { return proto.CompactTextString(m) }
func (*CompileResponse) ProtoMessage()    {}
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c90e492e3fe2f74, []int{2}
}

func (m *CompileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompileResponse.Unmarshal(m, b)
}
func (m *CompileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompileResponse.Marshal(b, m, deterministic)
}
func (m *CompileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompileResponse.Merge(m, src)
}
func (m *CompileResponse) XXX_Size() int {
	return xxx_messageInfo_CompileResponse.Size(m)
}
func (m *CompileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompileResponse proto.InternalMessageInfo

func (m *CompileResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CompileResponse) GetBuild() *Response {
	if m != nil {
		return m.Build
	}
	return nil
}

func (m *CompileResponse) GetExecute() *Response {
	if m != nil {
		return m.Execute
	}
	return nil
}

type Response struct {
	Log                  []string `protobuf:"bytes,1,rep,name=log,proto3" json:"log,omitempty"`
	Errors               []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	StartTime            int64    `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int64    `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Took                 int64    `protobuf:"varint,5,opt,name=took,proto3" json:"took,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c90e492e3fe2f74, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetLog() []string {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *Response) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *Response) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Response) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Response) GetTook() int64 {
	if m != nil {
		return m.Took
	}
	return 0
}

func init() {
	proto.RegisterType((*CompileRequest)(nil), "api.CompileRequest")
	proto.RegisterType((*File)(nil), "api.File")
	proto.RegisterType((*CompileResponse)(nil), "api.CompileResponse")
	proto.RegisterType((*Response)(nil), "api.Response")
}

func init() {
	proto.RegisterFile("compile.proto", fileDescriptor_9c90e492e3fe2f74)
}

var fileDescriptor_9c90e492e3fe2f74 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcb, 0x4b, 0xc3, 0x40,
	0x10, 0xc6, 0x4d, 0xb7, 0x69, 0x9b, 0xe9, 0x4b, 0xc6, 0x22, 0xa1, 0x08, 0x96, 0x78, 0x68, 0x4e,
	0x3d, 0xd4, 0xa3, 0xde, 0x84, 0x7a, 0x53, 0x58, 0xbc, 0x4b, 0x9a, 0x8c, 0xb2, 0x98, 0x66, 0xd7,
	0x64, 0x03, 0x3d, 0xfa, 0xa7, 0xcb, 0x4e, 0x92, 0x4a, 0xc1, 0xdb, 0x7c, 0xbf, 0x6f, 0x76, 0x1e,
	0x3b, 0x30, 0x4d, 0xf5, 0xc1, 0xa8, 0x9c, 0x36, 0xa6, 0xd4, 0x56, 0xa3, 0x48, 0x8c, 0x8a, 0x0c,
	0xcc, 0x9e, 0x1a, 0x2a, 0xe9, 0xbb, 0xa6, 0xca, 0xe2, 0x2d, 0xf8, 0x1f, 0x2a, 0xa7, 0x2a, 0xf4,
	0x56, 0x22, 0x1e, 0x6f, 0x83, 0x4d, 0x62, 0xd4, 0x66, 0xe7, 0x12, 0x1a, 0x8e, 0x0b, 0xf0, 0x55,
	0x61, 0x6a, 0x1b, 0xf6, 0x56, 0x22, 0x0e, 0x64, 0x23, 0x70, 0x0d, 0x73, 0x3a, 0x1a, 0x4a, 0x2d,
	0x65, 0xef, 0xba, 0xb6, 0xce, 0x17, 0xec, 0xcf, 0x3a, 0xfc, 0xca, 0x34, 0x7a, 0x84, 0xbe, 0xab,
	0x86, 0x4b, 0x18, 0xb9, 0x7a, 0x2f, 0xc9, 0x81, 0x42, 0x6f, 0xe5, 0xc5, 0x81, 0x3c, 0x69, 0x0c,
	0x61, 0x98, 0xea, 0xc2, 0x52, 0xe1, 0x9a, 0x78, 0xf1, 0x44, 0x76, 0x32, 0xd2, 0x30, 0x3f, 0xcd,
	0x5b, 0x19, 0x5d, 0x54, 0x84, 0x33, 0xe8, 0xa9, 0xac, 0x2d, 0xd1, 0x53, 0x19, 0xde, 0x81, 0xbf,
	0xaf, 0x55, 0x9e, 0xf1, 0xd3, 0xf1, 0x76, 0xca, 0x0b, 0x74, 0xd9, 0xb2, 0xf1, 0x70, 0x0d, 0x43,
	0x3a, 0x52, 0x5a, 0x5b, 0x0a, 0xc5, 0x7f, 0x69, 0x9d, 0x1b, 0xfd, 0x78, 0x30, 0x3a, 0xb5, 0xba,
	0x04, 0x91, 0xeb, 0x4f, 0xfe, 0x99, 0x40, 0xba, 0x10, 0xaf, 0x61, 0x40, 0x65, 0xa9, 0xcb, 0xaa,
	0xfd, 0x8d, 0x56, 0xe1, 0x0d, 0x04, 0x95, 0x4d, 0x4a, 0xfb, 0xa6, 0x0e, 0x4d, 0x07, 0x21, 0xff,
	0x80, 0xdb, 0x8f, 0x8a, 0x8c, 0xbd, 0x3e, 0x7b, 0x9d, 0x44, 0x84, 0xbe, 0xd5, 0xfa, 0x2b, 0xf4,
	0x19, 0x73, 0xbc, 0x7d, 0x86, 0x51, 0xbb, 0x73, 0x89, 0x0f, 0x30, 0x69, 0xe3, 0x1d, 0x1f, 0xe3,
	0x8a, 0xc7, 0x3e, 0x3f, 0xe1, 0x72, 0x71, 0x0e, 0x9b, 0xe1, 0xa3, 0x8b, 0xfd, 0x80, 0x0f, 0x7f,
	0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xe9, 0x5b, 0xcc, 0x09, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CompilerClient is the client API for Compiler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CompilerClient interface {
	CompileFiles(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error)
}

type compilerClient struct {
	cc grpc.ClientConnInterface
}

func NewCompilerClient(cc grpc.ClientConnInterface) CompilerClient {
	return &compilerClient{cc}
}

func (c *compilerClient) CompileFiles(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error) {
	out := new(CompileResponse)
	err := c.cc.Invoke(ctx, "/api.Compiler/CompileFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompilerServer is the server API for Compiler service.
type CompilerServer interface {
	CompileFiles(context.Context, *CompileRequest) (*CompileResponse, error)
}

// UnimplementedCompilerServer can be embedded to have forward compatible implementations.
type UnimplementedCompilerServer struct {
}

func (*UnimplementedCompilerServer) CompileFiles(ctx context.Context, req *CompileRequest) (*CompileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompileFiles not implemented")
}

func RegisterCompilerServer(s *grpc.Server, srv CompilerServer) {
	s.RegisterService(&_Compiler_serviceDesc, srv)
}

func _Compiler_CompileFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompilerServer).CompileFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Compiler/CompileFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompilerServer).CompileFiles(ctx, req.(*CompileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Compiler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Compiler",
	HandlerType: (*CompilerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompileFiles",
			Handler:    _Compiler_CompileFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compile.proto",
}
